# Generated by Django 4.2.6 on 2023-12-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_commentary_author_alter_mark_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=5000, null=True, verbose_name='Описание'),
        ),
    ]
